language: objective-c
osx_image: xcode7.3

before_install:
  - brew install swiftlint
  - gem install xcpretty
  - gem install cocoapods
  - gem install cocoapods-deploy

install:
  - pod deploy

script:
  - swiftlint
  - set -o pipefail && xcodebuild -workspace BothamNetworking.xcworkspace -scheme 'BothamNetworking' -destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -c
  - set -o pipefail && xcodebuild -workspace BothamNetworking.xcworkspace -scheme 'BothamNetworkingCocoa' build test | xcpretty -c