language: objective-c
osx_image: xcode8

before_install:
  - pod repo update --silent
  - gem install xcpretty

script:
  - swiftlint
  - set -o pipefail && xcodebuild -workspace BothamNetworking.xcworkspace -scheme 'BothamNetworking' -destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -c
  - set -o pipefail && xcodebuild -workspace BothamNetworking.xcworkspace -scheme 'BothamNetworkingCocoa' build test | xcpretty -c
